site_name: Documentação

nav:
  - Instruções mkdocs: "README.md"
  - Atas de Reunião:
    - Ata 1: "atas-reuniao/ata-reuniao-1.md"
  - Recursos:
    - Padrão de Commit: "recursos/padrões_commit.md"

theme:
  name: material
