site_name: Documentação

nav:
  - Instruções mkdocs: "README.md"
  - Atas de Reunião:
    - Ata 1: "docs/atas-reuniao/ata-reuniao-1.md"
    - Ata 2: "docs/atas-reuniao/ATA-reuniao-01.md"
  - Recursos:
    - Padrões de Commit: "docs/recursos/padrões_commit.md"

theme:
  name: material
