site_name: ConectaCiência

nav:
  - Introdução: "index.md"
  - Atas de Reunião:
    - Ata: "atas-reuniao/ata-padrao.md"
    - Ata 1: "atas-reuniao/ATA-Reunião-01.md"
    - Ata 2: "atas-reuniao/ATA-Reunião-02.md"
    - Ata 3: "atas-reuniao/ATA-Reunião-03.md"
    - Ata 4: "atas-reuniao/ATA-Reunião-04.md"
    - Ata 5: "atas-reuniao/ATA-Reunião-05.md"
    - Ata 6: "atas-reuniao/ATA-Reunião-06.md"
  
  - Gravações:
    - Planejamento de gravação de validação dos resultados: "Gravações/PlanejamentoGravacaoEquipe"
    - Planejamento de gravação de validação com cliente: "Gravações/PlanejamentoGravacaoCliente"
    - Relatório da gravação de validação com cliente: "Gravações/RelatorioGravacaoCliente.md"
    
  - Recursos:
    - Padrões de commit e branch: "recursos/padrões_commit.md"
    - Ferramentas: "recursos/tecnologias.md"
  - Relato do Cliente:
    - Sprint 1: "relato-cliente/relato-sprint1.md"
    - Sprint 2: "relato-cliente/relato-sprint2.md"

  - Tarefas: 
    - Regras de Negócio: "Tarefas/RegrasNegocio.md"
    - Requisitos do Sistema: "Tarefas/RequisitosSistema.md"
    - Visão do Produto: "Tarefas/VisaoProduto.md"
    - Modelagem de Processos: "Tarefas/ModelagemDeProcessos.md"
  - User Stories: 
    - MVP: "user-stories/MVP.md"
    - US:
      - US01: "user-stories/US01-Sobre.md"
      - US02: "user-stories/US02-Feed.md"
      - US03: "user-stories/US03-Filtros.md"
      - US04: "user-stories/US04-SugestaoTema.md"
      - US05: "user-stories/US05-SugestaoArtigo.md"
      - US06: "user-stories/US06-Cadastro.md"
      - US07: "user-stories/US07-Acesso.md"
      - US08: "user-stories/US08-Perfil.md"
      - US09: "user-stories/US09-Publicacao.md"
      - US010: "user-stories/US10-MeuArtigos.md"
      - US011: "user-stories/US11-EditarExcluir.md"
      - US012: "user-stories/US12-CurtirComentar.md"
      - US013: "user-stories/US13-PerfilPublico.md"
      - US014: "user-stories/US14-RecomendacoesFeed.md"
      - US015: "user-stories/US15-SeguirUsuarios.md"
      - US016: "user-stories/US16-Notificacoes.md"

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro
